// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooWebApp.Data;

#nullable disable

namespace ZooWebApp.Migrations
{
    [DbContext(typeof(ZooWebAppContext))]
    [Migration("20250910084140_animalMockDataV2")]
    partial class animalMockDataV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZooWebApp.Models.Animal", b =>
                {
                    b.Property<int>("AnimalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalID"));

                    b.Property<int>("AnimalAge")
                        .HasColumnType("int");

                    b.Property<string>("AnimalImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnimalName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfArrival")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MapImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("AnimalID");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            AnimalID = 1,
                            AnimalAge = 6,
                            AnimalImage = "images/animals/Jack.png",
                            AnimalName = "Jack",
                            DateOfArrival = new DateTime(2020, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Jack is a strong kangaroo who loves hopping around the enclosure.",
                            Gender = "M",
                            MapImage = "xxxx",
                            Species = "Kangaroo",
                            Weight = 85.00m
                        },
                        new
                        {
                            AnimalID = 2,
                            AnimalAge = 7,
                            AnimalImage = "images/animals/Leo.png",
                            AnimalName = "Leo",
                            DateOfArrival = new DateTime(2019, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Leo is the pride's leader with a majestic mane and a calm personality.",
                            Gender = "M",
                            MapImage = "xxxx",
                            Species = "Lion",
                            Weight = 190.00m
                        },
                        new
                        {
                            AnimalID = 3,
                            AnimalAge = 5,
                            AnimalImage = "images/animals/Shira.png",
                            AnimalName = "Shira",
                            DateOfArrival = new DateTime(2021, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shira is an agile tigress who enjoys swimming and stalking her toys.",
                            Gender = "F",
                            MapImage = "xxxx",
                            Species = "Tiger",
                            Weight = 160.00m
                        },
                        new
                        {
                            AnimalID = 4,
                            AnimalAge = 8,
                            AnimalImage = "images/animals/Stretch.png",
                            AnimalName = "Stretch",
                            DateOfArrival = new DateTime(2018, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stretch is a tall giraffe who loves reaching for the highest leaves.",
                            Gender = "M",
                            MapImage = "xxxx",
                            Species = "Giraffe",
                            Weight = 850.00m
                        },
                        new
                        {
                            AnimalID = 5,
                            AnimalAge = 6,
                            AnimalImage = "images/animals/Stripes.png",
                            AnimalName = "Stripes",
                            DateOfArrival = new DateTime(2020, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stripes is a lively zebra with bold markings and a playful spirit.",
                            Gender = "F",
                            MapImage = "xxxx",
                            Species = "Zebra",
                            Weight = 320.00m
                        },
                        new
                        {
                            AnimalID = 6,
                            AnimalAge = 9,
                            AnimalImage = "images/animals/Sonya.png",
                            AnimalName = "Sonya",
                            DateOfArrival = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sonya is a gentle bear who loves honey and naps by the trees.",
                            Gender = "F",
                            MapImage = "xxxx",
                            Species = "Bear",
                            Weight = 300.00m
                        },
                        new
                        {
                            AnimalID = 7,
                            AnimalAge = 4,
                            AnimalImage = "images/animals/Echo.png",
                            AnimalName = "Echo",
                            DateOfArrival = new DateTime(2022, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Echo is a curious bat who spends most of the day hanging upside down.",
                            Gender = "M",
                            MapImage = "xxxx",
                            Species = "Bat",
                            Weight = 1.20m
                        },
                        new
                        {
                            AnimalID = 8,
                            AnimalAge = 12,
                            AnimalImage = "images/animals/Bubbles.png",
                            AnimalName = "Bubbles",
                            DateOfArrival = new DateTime(2017, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bubbles is a hippo who loves wallowing in the water.",
                            Gender = "F",
                            MapImage = "xxxx",
                            Species = "Hippo",
                            Weight = 1500.00m
                        },
                        new
                        {
                            AnimalID = 9,
                            AnimalAge = 5,
                            AnimalImage = "images/animals/George.png",
                            AnimalName = "George",
                            DateOfArrival = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "George is an energetic monkey who is always up to mischief.",
                            Gender = "M",
                            MapImage = "xxxx",
                            Species = "Monkey",
                            Weight = 14.00m
                        },
                        new
                        {
                            AnimalID = 10,
                            AnimalAge = 7,
                            AnimalImage = "images/animals/Amber.png",
                            AnimalName = "Amber",
                            DateOfArrival = new DateTime(2019, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Amber is a thoughtful orangutan who enjoys solving puzzles.",
                            Gender = "F",
                            MapImage = "xxxx",
                            Species = "Orangutan",
                            Weight = 70.00m
                        },
                        new
                        {
                            AnimalID = 11,
                            AnimalAge = 15,
                            AnimalImage = "images/animals/Snap.png",
                            AnimalName = "Snap",
                            DateOfArrival = new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Snap is a powerful crocodile who enjoys basking on the riverbank.",
                            Gender = "M",
                            MapImage = "xxxx",
                            Species = "Crocodile",
                            Weight = 500.00m
                        },
                        new
                        {
                            AnimalID = 12,
                            AnimalAge = 14,
                            AnimalImage = "images/animals/Chomp.png",
                            AnimalName = "Chomp",
                            DateOfArrival = new DateTime(2019, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chomp is an alligator with a massive jaw, often spotted lurking under the water surface.",
                            Gender = "M",
                            MapImage = "xxxx",
                            Species = "Alligator",
                            Weight = 480.00m
                        },
                        new
                        {
                            AnimalID = 13,
                            AnimalAge = 11,
                            AnimalImage = "images/animals/Tank.png",
                            AnimalName = "Tank",
                            DateOfArrival = new DateTime(2021, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tank is a strong rhino with a calm demeanor, known for his large horn.",
                            Gender = "M",
                            MapImage = "xxxx",
                            Species = "Rhino",
                            Weight = 2100.00m
                        },
                        new
                        {
                            AnimalID = 14,
                            AnimalAge = 5,
                            AnimalImage = "images/animals/Capy.png",
                            AnimalName = "Capy",
                            DateOfArrival = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Capy is a social capybara who enjoys lounging by the water.",
                            Gender = "F",
                            MapImage = "xxxx",
                            Species = "Capybara",
                            Weight = 55.20m
                        },
                        new
                        {
                            AnimalID = 15,
                            AnimalAge = 7,
                            AnimalImage = "images/animals/Chewy.png",
                            AnimalName = "Chewy",
                            DateOfArrival = new DateTime(2021, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chewy is a busy beaver who spends hours building and repairing his lodge.",
                            Gender = "M",
                            MapImage = "xxxx",
                            Species = "Beaver",
                            Weight = 28.40m
                        },
                        new
                        {
                            AnimalID = 16,
                            AnimalAge = 13,
                            AnimalImage = "images/animals/Kong.png",
                            AnimalName = "Kong",
                            DateOfArrival = new DateTime(2019, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kong is a mighty gorilla with a gentle heart, often seen protecting his group.",
                            Gender = "M",
                            MapImage = "xxxx",
                            Species = "Gorilla",
                            Weight = 180.00m
                        },
                        new
                        {
                            AnimalID = 17,
                            AnimalAge = 2,
                            AnimalImage = "images/animals/Pebble.png",
                            AnimalName = "Pebble",
                            DateOfArrival = new DateTime(2023, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pebble is a young penguin who loves sliding across the ice.",
                            Gender = "F",
                            MapImage = "xxxx",
                            Species = "Penguin",
                            Weight = 8.30m
                        },
                        new
                        {
                            AnimalID = 18,
                            AnimalAge = 6,
                            AnimalImage = "images/animals/Julian.png",
                            AnimalName = "Julian",
                            DateOfArrival = new DateTime(2022, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Julian is a lively lemur who enjoys leaping from tree to tree.",
                            Gender = "M",
                            MapImage = "xxxx",
                            Species = "Lemur",
                            Weight = 9.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
