// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooWebApp.Data;

#nullable disable

namespace ZooWebApp.Migrations
{
    [DbContext(typeof(ZooWebAppContext))]
    [Migration("20250910035359_animalMockData")]
    partial class animalMockData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZooWebApp.Models.Animal", b =>
                {
                    b.Property<int>("AnimalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalID"));

                    b.Property<int>("AnimalAge")
                        .HasColumnType("int");

                    b.Property<string>("AnimalImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnimalName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfArrival")
                        .HasColumnType("Date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MapImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("AnimalID");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            AnimalID = 1,
                            AnimalAge = 5,
                            AnimalImage = "images/animals/leo.png",
                            AnimalName = "Leo",
                            DateOfArrival = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "M",
                            MapImage = "xxxx",
                            Species = "Lion",
                            Weight = 190.50m
                        },
                        new
                        {
                            AnimalID = 2,
                            AnimalAge = 3,
                            AnimalImage = "images/animals/joey.png",
                            AnimalName = "Joey",
                            DateOfArrival = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "F",
                            MapImage = "xxxx",
                            Species = "Kangaroo",
                            Weight = 85.75m
                        },
                        new
                        {
                            AnimalID = 3,
                            AnimalAge = 7,
                            AnimalImage = "images/animals/rajah.png",
                            AnimalName = "Rajah",
                            DateOfArrival = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "M",
                            MapImage = "xxxx",
                            Species = "Tiger",
                            Weight = 220.30m
                        },
                        new
                        {
                            AnimalID = 4,
                            AnimalAge = 12,
                            AnimalImage = "images/animals/grace.png",
                            AnimalName = "Grace",
                            DateOfArrival = new DateTime(2021, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "F",
                            MapImage = "xxxx",
                            Species = "Giraffe",
                            Weight = 800.40m
                        },
                        new
                        {
                            AnimalID = 5,
                            AnimalAge = 6,
                            AnimalImage = "images/animals/stripes.png",
                            AnimalName = "Stripes",
                            DateOfArrival = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "M",
                            MapImage = "xxxx",
                            Species = "Zebra",
                            Weight = 380.90m
                        },
                        new
                        {
                            AnimalID = 6,
                            AnimalAge = 2,
                            AnimalImage = "images/animals/echo.png",
                            AnimalName = "Echo",
                            DateOfArrival = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "F",
                            MapImage = "xxxx",
                            Species = "Bat",
                            Weight = 1.25m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
